name: "create release on main"
on:
  push:
    branches: 
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Cocogitto release
      id: release
      uses: oknozor/cocogitto-action@v3
      with:
        release: true
        git-user: 'Cog Bot'
        git-user-email: 'bot@kris.budd.ee'
    
    - name: Print version
      run: "echo '${{ steps.release.outputs.version }}'"
    
    - name: Push Tag
      run: |
        git push origin ${{ steps.release.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Generate Changelog
    #   run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md

    # - name: Upload github release
      # uses: softprops/action-gh-release@v1
    #   with:
    #     body_path: GITHUB_CHANGELOG.md
    #     tag_name: ${{ steps.release.outputs.version }}

  goreleaser:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0
      - 
        run: git fetch --force --tags
      - 
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
        with:
          go-version: stable
      # - 
      #   name: Docker Login
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - 
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ vars.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN}}
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # - 
      #   name: Docker Setup Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v2.10.0
      # -
      #   name: Available buildx platforms
      #   run: echo ${{ steps.buildx.outputs.platforms }}
      - 
        uses: goreleaser/goreleaser-action@3fa32b8bb5620a2c1afe798654bbad59f9da4906 # v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  