name: "create release on main"
on:
  push:
    branches: 
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0

    - name: Print version
      run: "echo '${{ steps.gitversion.outputs.semVer }}'"
    
    - name: Push Tag
      run: |
        git config user.email "pipeline@kris.budd.ee"
        git config user.name "Pipeline"
        git tag ${{ steps.gitversion.outputs.semVer }} -a -m "Release ${{ steps.gitversion.outputs.semVer }}"
        git push origin ${{ steps.gitversion.outputs.semVer }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



  goreleaser:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 0
      - 
        run: git fetch --force --tags
      - 
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5
        with:
          go-version: stable
      # - 
      #   name: Docker Login
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - 
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ vars.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN}}
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      # - 
      #   name: Docker Setup Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v2.10.0
      # -
      #   name: Available buildx platforms
      #   run: echo ${{ steps.buildx.outputs.platforms }}
      - 
        uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  